// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoListApp.WebApi.Repository;

#nullable disable

namespace TodoListApp.WebApi.Migrations
{
    [DbContext(typeof(TodoListDbContext))]
    [Migration("20250209135921_SeedTask")]
    partial class SeedTask
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TagEntityTaskEntity", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.Property<int>("TasksId")
                        .HasColumnType("int");

                    b.HasKey("TagsId", "TasksId");

                    b.HasIndex("TasksId");

                    b.ToTable("TagEntityTaskEntity");
                });

            modelBuilder.Entity("TodoListApp.WebApi.Repository.Entities.CommentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<int>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("comment");
                });

            modelBuilder.Entity("TodoListApp.WebApi.Repository.Entities.StatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.ToTable("task_status");
                });

            modelBuilder.Entity("TodoListApp.WebApi.Repository.Entities.TagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("tag");
                });

            modelBuilder.Entity("TodoListApp.WebApi.Repository.Entities.TaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("task_status_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<int?>("TodoListId")
                        .HasColumnType("int")
                        .HasColumnName("todolist_id");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("TodoListId");

                    b.ToTable("task");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description1",
                            Title = "Task1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description2",
                            Title = "Task2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description3",
                            Title = "Task3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description4",
                            Title = "Task4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description5",
                            Title = "Task5"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description6",
                            Title = "Task6"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Description7",
                            Title = "Task7"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Description8",
                            Title = "Task8"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Description9",
                            Title = "Task9"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Description10",
                            Title = "Task10"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Description11",
                            Title = "Task11"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Description12",
                            Title = "Task12"
                        });
                });

            modelBuilder.Entity("TodoListApp.WebApi.Repository.Entities.TodoListEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("todo_list");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description1",
                            Title = "TodoList1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description2",
                            Title = "TodoList2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description3",
                            Title = "TodoList3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description4",
                            Title = "TodoList4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description5",
                            Title = "TodoList5"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description6",
                            Title = "TodoList6"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Description7",
                            Title = "TodoList7"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Description8",
                            Title = "TodoList8"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Description9",
                            Title = "TodoList9"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Description10",
                            Title = "TodoList10"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Description11",
                            Title = "TodoList11"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Description12",
                            Title = "TodoList12"
                        });
                });

            modelBuilder.Entity("TagEntityTaskEntity", b =>
                {
                    b.HasOne("TodoListApp.WebApi.Repository.Entities.TagEntity", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoListApp.WebApi.Repository.Entities.TaskEntity", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TodoListApp.WebApi.Repository.Entities.CommentEntity", b =>
                {
                    b.HasOne("TodoListApp.WebApi.Repository.Entities.TaskEntity", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TodoListApp.WebApi.Repository.Entities.TaskEntity", b =>
                {
                    b.HasOne("TodoListApp.WebApi.Repository.Entities.StatusEntity", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.HasOne("TodoListApp.WebApi.Repository.Entities.TodoListEntity", "TodoList")
                        .WithMany()
                        .HasForeignKey("TodoListId");

                    b.Navigation("Status");

                    b.Navigation("TodoList");
                });
#pragma warning restore 612, 618
        }
    }
}
